language: csharp
dist: trusty
mono: none
sudo: required
dotnet: 1.0.1

os:
  - linux
  - osx
  
before_script:
  - dotnet restore src/stashbox.sln

script:
  - dotnet test src/stashbox.tests/stashbox.tests.csproj -c Release -f netcoreapp1.0

notifications:
  slack: stashbox-container:h2wOfP7OIteSvf9KJ3j64gZD
