environment:
  github_auth_token:
    secure: z/dKTRVRPmpItPTM/lYdX7dBJk3roDLV98Uj1XzpDqqV868xhHX8dnyKwPAJooUj

deploy:
- provider: NuGet
  server: https://www.myget.org/F/pcsajtai/api/v2/package
  symbol_server: https://www.myget.org/F/pcsajtai/symbols/api/v2/package
  api_key:
    secure: 2bITagXOj2s3bTJaGXh8/iyWtST8OQOFaMM+0GAKgZts9OjCVCiV7C+E/0SYsM6M

skip_tags: true

image: Visual Studio 2017

configuration: Release

install:
- ps: |
    $ver = Get-Content ".version"
    Update-AppveyorBuild -Version "$ver-preview-${env:APPVEYOR_BUILD_NUMBER}"
    choco install "msbuild-sonarqube-runner" -y

before_build:
- ps: . .\patch-version.ps1 "src\stashbox\stashbox.csproj" ${env:APPVEYOR_BUILD_VERSION}
- ps: if ($env:APPVEYOR_PULL_REQUEST_NUMBER) { MSBuild.SonarQube.Runner.exe begin /k:"stashbox" /d:"sonar.host.url=https://sonarqube.com" /d:"sonar.login=b6dc58c52583ce0876897344c40fd40d7d8e57de" /o:"z4kn4fein-github" /d:"sonar.analysis.mode=preview" /d:"sonar.github.pullRequest=$env:APPVEYOR_PULL_REQUEST_NUMBER" /d:"sonar.github.repository=z4kn4fein/stashbox" /d:"sonar.github.oauth=$env:github_auth_token" /v:${env:APPVEYOR_BUILD_VERSION} }
- ps: if (-Not $env:APPVEYOR_PULL_REQUEST_NUMBER) { MSBuild.SonarQube.Runner.exe begin /k:"stashbox" /d:"sonar.host.url=https://sonarqube.com" /d:"sonar.login=b6dc58c52583ce0876897344c40fd40d7d8e57de" /o:"z4kn4fein-github" /v:${env:APPVEYOR_BUILD_VERSION} }

build_script:
- msbuild /t:Restore /p:Configuration=%CONFIGURATION% src\stashbox.sln
- msbuild /t:Build /p:Configuration=%CONFIGURATION% src\stashbox.sln

after_build:
- SonarQube.Scanner.MSBuild.exe end /d:"sonar.login=b6dc58c52583ce0876897344c40fd40d7d8e57de"
- msbuild /t:Pack /p:IncludeSymbols=true /p:Configuration=%CONFIGURATION% /p:PackageOutputPath=..\..\artifacts src\stashbox\stashbox.csproj

test_script:
- dotnet test src\stashbox.tests\stashbox.tests.csproj  -f net45 -c %CONFIGURATION% --no-build
- dotnet test src\stashbox.tests\stashbox.tests.csproj  -f netcoreapp1.0 -c %CONFIGURATION% --no-build
- dotnet test src\stashbox.tests\stashbox.tests.csproj  -f netcoreapp2.0 -c %CONFIGURATION% --no-build

after_test:
- ps: . .\set-debug-type.ps1 "src\stashbox\stashbox.csproj"
- ps: . .\coverage.ps1

artifacts:
- path: artifacts\Stashbox.*.nupkg
  name: NuGet

notifications:
- provider: Email
  to:
  - peter.csajtai@outlook.com
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: true

- provider: Slack
  auth_token:
    secure: /KAOQIEOWc7w1EUl6J01qNam+f+ujntrwh53yJ0zg4qRWsdfWbkjKP2UG7tQDW7/hSVJHqF7Hz/IPdS6Cp5ilsfgH6xYroLB/sawQ/pdC5k=
  channel: '#ci'