deploy:
- provider: NuGet
  on:
    branch: master
  api_key:
    secure: doqtwSE1NadH7pf4jqYifDu4tcXzsNiJtPWOccnbUrhSnIJX+5js7m8z+kV9LNJ2

- provider: GitHub
  tag: $(build_version)
  release: Stashbox v$(build_version)
  on:
    branch: master
  auth_token:
    secure: TaIug8cHioxT2qDznFpGtDinZiDi+20pEMQZUVAATWCvGLG9Y5LrjaxDUQtGyt38
  artifact: /.*\.nupkg/

environment:
  build_version: ''

image: Visual Studio 2017

configuration: Release

init:
- ps: |
    $env:build_version = Get-Content ".version"
    Update-AppveyorBuild -Version "${env:build_version}-${env:APPVEYOR_BUILD_NUMBER}"

before_build:
- ps: . .\patch-version.ps1 "src\stashbox\stashbox.csproj"  ${env:build_version}

build_script:
- msbuild /t:Restore /p:Configuration=%CONFIGURATION% src\stashbox.sln
- msbuild /t:Build /p:Configuration=%CONFIGURATION% src\stashbox.sln

after_build:
- msbuild /t:Pack /p:IncludeSymbols=true /p:Configuration=%CONFIGURATION% /p:PackageOutputPath=..\..\artifacts src\stashbox\stashbox.csproj

artifacts:
- path: artifacts\Stashbox.*.nupkg
  name: NuGet

notifications:
- provider: Email
  to:
  - peter.csajtai@outlook.com
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: true

- provider: Slack
  auth_token:
    secure: /KAOQIEOWc7w1EUl6J01qNam+f+ujntrwh53yJ0zg4qRWsdfWbkjKP2UG7tQDW7/hSVJHqF7Hz/IPdS6Cp5ilsfgH6xYroLB/sawQ/pdC5k=
  channel: '#ci'