deploy:
- provider: NuGet
  server: https://www.myget.org/F/pcsajtai/api/v2/package
  symbol_server: https://www.myget.org/F/pcsajtai/symbols/api/v2/package
  api_key:
    secure: 2bITagXOj2s3bTJaGXh8/iyWtST8OQOFaMM+0GAKgZts9OjCVCiV7C+E/0SYsM6M

skip_tags: true

pull_requests:
  do_not_increment_build_number: true

image: Visual Studio 2017

configuration: Release

install:
- ps: |
    $ver = Get-Content ".version"
    Update-AppveyorBuild -Version "$ver-preview-${env:APPVEYOR_BUILD_NUMBER}"

before_build:
- ps: . .\patch-version.ps1 "src\stashbox\stashbox.csproj"  ${env:APPVEYOR_BUILD_VERSION}

build_script:
- msbuild /t:Restore /p:Configuration=%CONFIGURATION% src\stashbox.sln
- msbuild /t:Build /p:Configuration=%CONFIGURATION% src\stashbox.sln

after_build:
- msbuild /t:Pack /p:IncludeSymbols=true /p:Configuration=%CONFIGURATION% /p:PackageOutputPath=..\..\artifacts src\stashbox\stashbox.csproj

test_script:
- dotnet test src\stashbox.tests\stashbox.tests.csproj  -f net45 -c %CONFIGURATION% --no-build
- dotnet test src\stashbox.tests\stashbox.tests.csproj  -f netcoreapp1.0 -c %CONFIGURATION% --no-build

after_test:
- ps: . .\set-debug-type.ps1 "src\stashbox\stashbox.csproj"
- ps: . .\coverage.ps1

artifacts:
- path: artifacts\Stashbox.*.nupkg
  name: NuGet

notifications:
- provider: Email
  to:
  - peter.csajtai@outlook.com
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: true

- provider: Slack
  auth_token:
    secure: /KAOQIEOWc7w1EUl6J01qNam+f+ujntrwh53yJ0zg4qRWsdfWbkjKP2UG7tQDW7/hSVJHqF7Hz/IPdS6Cp5ilsfgH6xYroLB/sawQ/pdC5k=
  channel: '#ci'